name: Test action workflow

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check the tags
        run: git tag
      - uses: ./
        with:
          release_tag: "1.0.1"
